FROM node:20-alpine

# pindah ke direktori app
WORKDIR /app

# duplikasi file package.json package-lock.json
COPY package.json package-lock.json ./

# install seluruh dependency 
RUN npm install -g npm@10.8.0
RUN npm install


ENTRYPOINT [ "docker-entrypoint.sh" ]

# jalankan npm run dev
CMD [ "npm","run","dev" ]